server:
  port: 9999
spring:
  rabbitmq:
    host: 49.232.17.193
    port: 5672
    username: liangpan
    password: 123456
    virtual-host: guxingyuan
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 2