server:
  port: 9999
spring:
  rabbitmq:
    host: 49.232.17.193
    port: 5672
    username: liangpan
    password: 123456
    virtual-host: guxingyuan
    listener:
      simple:
        acknowledge-mode: manual  #采用手工确认模式
        prefetch: 20  # 配置Prefetch count数值
        concurrency: 5  #指定最小的消费数量，程序中优先
        max-concurrency: 50  #制定最大的消费数量
        retry:
          enabled: true # 是否支持重试
