#服务信息
server:
  info: liangpanpan
  port: 8081

# Spring信息
spring:
  #界面模板信息
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  #Redis
  redis:
    database: 0
    timeout: 1000
    password: liangpan
    cluster:
      nodes:
        - 49.232.17.193:8001
        - 49.232.17.193:8002
        - 49.232.17.193:8003
        - 49.232.17.193:8004
        - 49.232.17.193:8005
        - 49.232.17.193:8006
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 50
        max-wait: 1000

  # 数据库配置
  datasource:
    url: jdbc:mysql://49.232.17.193:3306/guxingyuan?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数