#服务信息
server:
  info: liangpanpan
  port: 8081

# Spring信息
spring:
  #界面模板信息
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  #Redis
  redis:
    database: 0
    timeout: 1000
    password: liangpan
    cluster:
      nodes:
        - 140.143.119.132:8001
        - 140.143.119.132:8002
        - 140.143.119.132:8003
        - 140.143.119.132:8004
        - 140.143.119.132:8005
        - 140.143.119.132:8006
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 50
        max-wait: 1000

  # 数据库配置
  datasource:
    url: jdbc:mysql://140.143.119.132:3306/guxingyuan?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lpp@123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数