server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://49.232.17.193:3306/guxingyuan?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数

timing-task:
  cron1: 0/2 * * * * ?
  cron2: 0/5 * * * * ?
