server:
  port: 8088

spring:
  servlet:
    multipart:
      # 根据实际需求作调整
      # 默认最大上传文件大小为1M，单个文件大小
      max-file-size: -1
      # 默认最大请求大小为10M，总上传的数据大小
      max-request-size: -1
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://140.143.119.132:3306/guxingyuan?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lpp@123456
    # 初始化，最小，最大连接数
    initialSize: 5
    minIdle: 5
    maxActive: 25
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual

  mvc:
    servlet:
      load-on-startup: 1
    converters:
      preferred-json-mapper: gson

mybatis:
  # 配置上别名后，mapper.xml中的resultType可以直接采用对象类名，不用再添加包名
  type-aliases-package: com.guxingyuan.mybatis.entity
  mapper-locations: classpath:mappers/**.xml
  check-config-location: true
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 输出到控制台
    #      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    # 使用slf4j日志插件
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


# page helper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

logging:
# 优先顺序 启动脚本指定->yml配置文件指定->resources文件夹中存放logback.xml
#  config: classpath:logback-${spring.profiles.active}-spring.xml
  level:
    com.guxingyuan.mybatis.mapper: debug
    root: info
  file:
    name: /var/log/mybatis/app.log  # 日志文件名称 ，支持相对路径和绝对路径
  pattern:
    # 控制台输出格式
    console: "%magenta(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%yellow(%thread)] %highlight(%-5level) %cyan(%logger{36} [%L] -) %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%L] - %msg%n"  # 文件输出格式
  logback:
    rollingPolicy:
      file-name-pattern: /var/log/mybatis/archived/app.%d{yyyy-MM-dd}.%i.log.gz  # 归档文件名格式
      max-file-size: 10MB  # 每个日志文件的最大大小
      max-history: 30     # 保留的归档文件数量