#服务信息
server:
  port: 8081

# Spring信息
spring:
  #Redis
  redis:
#    host: 140.143.119.132
    host: 192.168.30.185
    port: 6379
    timeout: 1000
    password:
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 50
        max-wait: 1000

# 还可以使用jedis，使用jedis的话，需要在spring-boot-starter-data-redis 中去除
#    <exclusion>
#    <groupId>io.lettuce</groupId>
#    <artifactId>lettuce-core</artifactId>
#    </exclusion>
# 然后添加
#        <dependency>
#          <groupId>org.apache.commons</groupId>
#          <artifactId>commons-pool2</artifactId>
#        </dependency>
#        <dependency>
#          <groupId>redis.clients</groupId>
#          <artifactId>jedis</artifactId>
#        </dependency>
# 将lettuce更好成jedis
#    jedis:
#      pool:
#        max-active: 100
#        min-idle: 10
#        max-idle: 50
#        max-wait: 1000
